#メインブランチへのプッシュ
name: Push to Branch

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create and push branch
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git checkout -b new-branch
          echo "New content" > newfile.txt
          git add .
          git commit -m "Add new file"
          git push origin new-branch
